name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch
        run: |
          BRANCH_NAME="update-$(date +'%Y%m%d%H%M%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME

      - name: Make a change
        run: |
          echo "// Change added at $(date)" >> changes.txt
          git add changes.txt
          git commit -m "Auto update at $(date)"

      - name: Push branch
        run: |
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR commit"
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated Pull Request"
          body: "This PR was created automatically by workflow"
          labels: automated
